import type { Protocol } from "./types";

export const PROTOCOLS: Protocol[] = [
  {
    id: "uni",
    name: "Uniswap",
    symbol: "UNI",
    category: "DEX",
    networks: ["Ethereum", "Base", "Polygon"],
    tags: ["dex", "defi"],
    lat: 40.7128,
    lng: -74.006,
    country: "United States",
    logo: "/protocol-logos/uniswap.webp",
    description: "Automated liquidity and swap routing across EVM markets.",
    website: "https://uniswap.org",
  },
  {
    id: "ray",
    name: "Raydium",
    symbol: "RAY",
    category: "DEX",
    networks: ["Solana"],
    tags: ["dex", "solana"],
    lat: 1.3521,
    lng: 103.8198,
    country: "Singapore",
    logo: "/protocol-logos/raydium.webp",
    description: "Solana AMM and orderbook liquidity venue.",
    website: "https://raydium.io",
  },
  {
    id: "aave",
    name: "Aave",
    symbol: "AAVE",
    category: "Lending",
    networks: ["Ethereum", "Arbitrum", "Optimism"],
    tags: ["lending", "money-market"],
    lat: 51.5072,
    lng: -0.1276,
    country: "United Kingdom",
    logo: "/protocol-logos/aave.webp",
    description: "Collateralized liquidity markets for borrowing and lending.",
    website: "https://aave.com",
  },
  {
    id: "maker",
    name: "Sky",
    symbol: "SKY",
    category: "Stablecoin",
    networks: ["Ethereum"],
    tags: ["stablecoin", "governance"],
    lat: 55.6761,
    lng: 12.5683,
    country: "Denmark",
    logo: "/protocol-logos/makerdao.webp",
    description: "Decentralized credit and stablecoin infrastructure.",
    website: "https://sky.money",
  },
  {
    id: "jup",
    name: "Jupiter",
    symbol: "JUP",
    category: "DEX",
    networks: ["Solana"],
    tags: ["aggregator", "solana"],
    lat: 13.7563,
    lng: 100.5018,
    country: "Thailand",
    logo: "/protocol-logos/jupiter.webp",
    description: "Solana liquidity aggregation and routing engine.",
    website: "https://jup.ag",
  },
  {
    id: "navi",
    name: "NAVI",
    symbol: "NAVI",
    category: "Lending",
    networks: ["Sui"],
    tags: ["lending", "sui"],
    lat: 1.3521,
    lng: 103.8198,
    country: "Singapore",
    logo: "https://icons.llama.fi/navi-lending.jpg",
    description: "Sui-native lending market for supplying, borrowing, and looping core ecosystem assets.",
    website: "https://www.naviprotocol.io/",
  },
  {
    id: "suilend",
    name: "Suilend",
    symbol: "SEND",
    category: "Lending",
    networks: ["Sui"],
    tags: ["lending", "sui"],
    lat: 37.7749,
    lng: -122.4194,
    country: "United States",
    logo: "https://icons.llama.fi/suilend.png",
    description: "Money-market protocol bringing borrow and lend primitives to Sui assets.",
    website: "https://www.suilend.fi",
  },
  {
    id: "alphalend",
    name: "AlphaLend",
    symbol: "ALPHA",
    category: "Lending",
    networks: ["Sui"],
    tags: ["lending", "bluefin", "sui"],
    lat: 22.3193,
    lng: 114.1694,
    country: "Hong Kong",
    logo: "https://icons.llama.fi/alphalend.png",
    description: "Sui lending venue connected to Bluefin liquidity and trader collateral workflows.",
    website: "https://trade.bluefin.io/lend",
  },
  {
    id: "springsui",
    name: "SpringSui",
    symbol: "sSUI",
    category: "Staking",
    networks: ["Sui"],
    tags: ["liquid-staking", "sui"],
    lat: 47.6062,
    lng: -122.3321,
    country: "United States",
    logo: "https://icons.llama.fi/spring-sui.png",
    description: "Liquid staking standard for SUI-backed positions and DeFi collateral on Sui.",
    website: "https://springsui.com/",
  },
  {
    id: "haedal",
    name: "Haedal",
    symbol: "HAEDAL",
    category: "Staking",
    networks: ["Sui"],
    tags: ["liquid-staking", "sui"],
    lat: 35.6762,
    lng: 139.6503,
    country: "Japan",
    logo: "https://icons.llama.fi/haedal-protocol.jpg",
    description: "Liquid staking protocol for SUI with receipt assets used across Sui DeFi.",
    website: "https://haedal.xyz",
  },
  {
    id: "cetus",
    name: "Cetus",
    symbol: "CETUS",
    category: "DEX",
    networks: ["Sui", "Aptos"],
    tags: ["dex", "clmm", "sui"],
    lat: 1.3521,
    lng: 103.8198,
    country: "Singapore",
    logo: "https://icons.llama.fi/cetus-clmm.png",
    description: "Concentrated liquidity AMM serving Sui spot pairs and liquidity providers.",
    website: "https://www.cetus.zone",
  },
  {
    id: "scallop",
    name: "Scallop",
    symbol: "SCA",
    category: "Lending",
    networks: ["Sui"],
    tags: ["lending", "sui"],
    lat: 51.5072,
    lng: -0.1276,
    country: "United Kingdom",
    logo: "https://icons.llama.fi/scallop-lend.jpg",
    description: "Sui lending protocol with money markets, collateral management, and yield vaults.",
    website: "https://app.scallop.io",
  },
  {
    id: "bluefin",
    name: "Bluefin",
    symbol: "BLUE",
    category: "DEX",
    networks: ["Sui"],
    tags: ["dex", "spot", "sui"],
    lat: 25.2048,
    lng: 55.2708,
    country: "United Arab Emirates",
    logo: "https://icons.llama.fi/bluefin-spot.png",
    description: "Sui spot trading venue with concentrated liquidity and exchange-style execution.",
    website: "https://bluefin.io",
  },
  {
    id: "deepbook",
    name: "DeepBook",
    symbol: "DEEP",
    category: "DEX",
    networks: ["Sui"],
    tags: ["dex", "orderbook", "sui"],
    lat: 50.1109,
    lng: 8.6821,
    country: "Germany",
    logo: "https://icons.llama.fi/deepbook-v3.jpg",
    description: "Native Sui central limit order book used as shared liquidity infrastructure.",
    website: "https://deepbook.tech",
  },
  {
    id: "volo-lst",
    name: "Volo",
    symbol: "vSUI",
    category: "Staking",
    networks: ["Sui"],
    tags: ["liquid-staking", "sui"],
    lat: 52.52,
    lng: 13.405,
    country: "Germany",
    logo: "https://icons.llama.fi/volo-lst.jpg",
    description: "Liquid staking token protocol for SUI staking yield and composable collateral.",
    website: "https://www.volosui.com/",
  },
  {
    id: "bucket",
    name: "Bucket",
    symbol: "BUCK",
    category: "DeFi",
    networks: ["Sui"],
    tags: ["cdp", "farm", "stablecoin", "sui"],
    lat: 35.6895,
    lng: 139.6917,
    country: "Japan",
    logo: "https://icons.llama.fi/bucket-cdp.jpg",
    description: "Bucket ecosystem for Sui-backed stablecoin positions, CDP borrowing, and farm liquidity.",
    website: "https://bucketprotocol.io",
  },
  {
    id: "current",
    name: "Current",
    symbol: "CURRENT",
    category: "Lending",
    networks: ["Sui"],
    tags: ["lending", "sui"],
    lat: 40.7128,
    lng: -74.006,
    country: "United States",
    logo: "https://icons.llama.fi/current.jpg",
    description: "Sui lending market for active borrowers, suppliers, and yield strategies.",
    website: "https://www.current.finance/",
  },
  {
    id: "alphafi",
    name: "AlphaFi",
    symbol: "ALPHA",
    category: "DeFi",
    networks: ["Sui"],
    tags: ["yield-aggregator", "sui"],
    lat: 13.7563,
    lng: 100.5018,
    country: "Thailand",
    logo: "https://icons.llama.fi/alphafi-agg.jpg",
    description: "Yield aggregator for Sui vaults, farms, and automated DeFi strategies.",
    website: "https://alphafi.xyz",
  },
  {
    id: "momentum",
    name: "Momentum",
    symbol: "MMT",
    category: "DEX",
    networks: ["Sui"],
    tags: ["dex", "sui"],
    lat: 37.5665,
    lng: 126.978,
    country: "South Korea",
    logo: "https://icons.llama.fi/momentum.jpg",
    description: "Sui DEX focused on swap liquidity, incentives, and ecosystem trading campaigns.",
    website: "https://app.mmt.finance/trade",
  },
  {
    id: "curve",
    name: "Curve",
    symbol: "CRV",
    category: "DEX",
    networks: ["Ethereum", "Optimism", "Fantom"],
    tags: ["dex", "stable-swap"],
    lat: 46.2044,
    lng: 6.1432,
    country: "Switzerland",
    logo: "/protocol-logos/curve.webp",
    description: "Stable asset exchange and liquidity incentives.",
    website: "https://curve.fi",
  },
  {
    id: "lido",
    name: "Lido",
    symbol: "LDO",
    category: "Staking",
    networks: ["Ethereum", "Polygon"],
    tags: ["staking", "liquid-staking"],
    lat: 52.52,
    lng: 13.405,
    country: "Germany",
    logo: "/protocol-logos/lido.webp",
    description: "Liquid staking protocol for proof-of-stake networks.",
    website: "https://lido.fi",
  },
  {
    id: "gmx",
    name: "GMX",
    symbol: "GMX",
    category: "DEX",
    networks: ["Arbitrum", "Avalanche"],
    tags: ["perps", "dex"],
    lat: 25.2048,
    lng: 55.2708,
    country: "United Arab Emirates",
    logo: "/protocol-logos/gmx.webp",
    description: "On-chain perpetuals and spot trading liquidity.",
    website: "https://gmx.io",
  },
  {
    id: "comp",
    name: "Compound",
    symbol: "COMP",
    category: "Lending",
    networks: ["Ethereum", "Base"],
    tags: ["lending"],
    lat: 37.7749,
    lng: -122.4194,
    country: "United States",
    logo: "/protocol-logos/compound.webp",
    description: "Algorithmic money markets for crypto assets.",
    website: "https://compound.finance",
  },
  {
    id: "dydx",
    name: "dYdX",
    symbol: "DYDX",
    category: "DEX",
    networks: ["dYdX Chain"],
    tags: ["perps", "derivatives"],
    lat: 35.6762,
    lng: 139.6503,
    country: "Japan",
    logo: "/protocol-logos/dydx.webp",
    description: "Decentralized derivatives trading infrastructure.",
    website: "https://dydx.exchange",
  },
];

export function formatCoordinate(value: number, axis: "lat" | "lng") {
  const direction =
    axis === "lat" ? (value >= 0 ? "N" : "S") : value >= 0 ? "E" : "W";
  return `${Math.abs(value).toFixed(2)}°${direction}`;
}

export function formatProtocolLocation(protocol: Protocol) {
  return `${protocol.country} · ${formatCoordinate(protocol.lat, "lat")} ${formatCoordinate(
    protocol.lng,
    "lng",
  )}`;
}
